-- NexusCargo Seafood Ops, v1. One export order corresponds to one shipment.
-- Migrations are applied by A only; this file contains no real customer data.

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  role text not null check (role in ('OPERATOR', 'DOCUMENT_STAFF', 'MANAGER')),
  created_at timestamptz not null default now()
);
create index memberships_org_idx on public.memberships(org_id);

-- The synthetic staff directory is separate from Auth users. A may link staff
-- records to real accounts later; no demo credentials are generated by seed.
create table public.staff (
  id text primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  display_name text not null,
  role text not null check (role in ('OPERATOR', 'DOCUMENT_STAFF', 'MANAGER'))
);
create index staff_org_idx on public.staff(org_id);

create table public.shipments (
  id text primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  order_no text not null,
  booking_no text,
  booking_version integer not null check (booking_version >= 1),
  product text not null check (product in ('SHRIMP', 'PANGASIUS')),
  customer_name text not null,
  destination text,
  vessel_name text,
  voyage_no text,
  etd timestamptz,
  si_cutoff timestamptz,
  vgm_cutoff timestamptz,
  cy_cutoff timestamptz,
  status text not null check (status in ('READY', 'AT_RISK', 'BLOCKED', 'COMPLETED')),
  priority text not null check (priority in ('CRITICAL', 'HIGH', 'NORMAL')),
  urgency_rank smallint not null check (urgency_rank between 0 and 3),
  next_action_at timestamptz,
  risk_reasons text[] not null default '{}',
  assignee_name text,
  container_count integer not null default 0 check (container_count >= 0),
  required_set_point_celsius numeric(5, 1),
  updated_at timestamptz not null default now(),
  unique (org_id, order_no)
);
create index shipments_org_status_idx on public.shipments(org_id, status, urgency_rank, next_action_at, id);
create index shipments_org_product_idx on public.shipments(org_id, product, status, id);
create index shipments_org_etd_idx on public.shipments(org_id, etd, id);

create table public.containers (
  id text primary key,
  shipment_id text not null references public.shipments(id) on delete cascade,
  container_no text,
  seal_no text,
  set_point_celsius numeric(5, 1),
  reefer_connection_confirmed boolean not null default false
);
create index containers_shipment_idx on public.containers(shipment_id);

create table public.documents (
  id text primary key,
  shipment_id text not null references public.shipments(id) on delete cascade,
  order_no text not null,
  type text not null check (type in ('BOOKING', 'SI', 'VGM', 'HEALTH_CERTIFICATE', 'CUSTOMS_RELEASE', 'GATE_IN_RECEIPT', 'OTHER')),
  status text not null check (status in ('PROCESSING', 'PENDING_REVIEW', 'VERIFIED', 'STALE', 'REJECTED', 'FAILED')),
  file_name text not null,
  version integer not null check (version >= 1),
  review_id text unique,
  extracted_fields jsonb not null default '[]'::jsonb check (jsonb_typeof(extracted_fields) = 'array'),
  uploaded_at timestamptz not null,
  reviewed_at timestamptz
);
create index documents_shipment_idx on public.documents(shipment_id, type, version);
create index documents_review_idx on public.documents(status, uploaded_at, id);

create table public.checks (
  id text primary key,
  shipment_id text not null references public.shipments(id) on delete cascade,
  code text not null,
  title text not null,
  status text not null check (status in ('PASS', 'MISSING', 'MISMATCH', 'PENDING_REVIEW', 'STALE')),
  message text not null,
  related_document_ids text[] not null default '{}',
  required_by timestamptz,
  updated_at timestamptz not null,
  unique (shipment_id, code)
);
create index checks_shipment_idx on public.checks(shipment_id);

create table public.tasks (
  id text primary key,
  shipment_id text not null references public.shipments(id) on delete cascade,
  order_no text not null,
  source_check_code text not null,
  title text not null,
  description text not null,
  status text not null check (status in ('OPEN', 'IN_PROGRESS', 'DONE')),
  status_rank smallint not null check (status_rank between 0 and 1),
  priority text not null check (priority in ('CRITICAL', 'HIGH', 'NORMAL')),
  priority_rank smallint not null check (priority_rank between 0 and 2),
  assignee_id text references public.staff(id),
  assignee_name text,
  due_at timestamptz,
  latest_start_at timestamptz,
  evidence_document_id text references public.documents(id),
  completion_note text,
  version integer not null default 1 check (version >= 1),
  updated_at timestamptz not null
);
create index tasks_shipment_idx on public.tasks(shipment_id);
create index tasks_urgency_idx on public.tasks(status_rank, priority_rank, latest_start_at, id);

create table public.audit_events (
  id text primary key,
  shipment_id text not null references public.shipments(id) on delete cascade,
  actor_name text not null,
  action text not null,
  description text not null,
  created_at timestamptz not null
);
create index audit_events_shipment_idx on public.audit_events(shipment_id, created_at desc);

-- Membership lookup is owned by postgres (BYPASSRLS on Supabase). The private
-- schema is not exposed by PostgREST; use it only from row policies.
create schema if not exists private;
create function private.current_org_id()
returns uuid language sql stable security definer set search_path = ''
as $$
  select m.org_id from public.memberships m
  where m.user_id = (select auth.uid())
  limit 1
$$;
revoke all on function private.current_org_id() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.current_org_id() to authenticated;

alter table public.organizations enable row level security;
alter table public.memberships enable row level security;
alter table public.staff enable row level security;
alter table public.shipments enable row level security;
alter table public.containers enable row level security;
alter table public.documents enable row level security;
alter table public.checks enable row level security;
alter table public.tasks enable row level security;
alter table public.audit_events enable row level security;

create policy "members read own organization" on public.organizations
  for select to authenticated using (id = (select private.current_org_id()));
create policy "members read own membership" on public.memberships
  for select to authenticated using (user_id = (select auth.uid()));
create policy "members read staff" on public.staff
  for select to authenticated using (org_id = (select private.current_org_id()));
create policy "members read shipments" on public.shipments
  for select to authenticated using (org_id = (select private.current_org_id()));

create policy "members read containers" on public.containers
  for select to authenticated using (
    exists (select 1 from public.shipments s
            where s.id = shipment_id and s.org_id = (select private.current_org_id()))
  );
create policy "members read documents" on public.documents
  for select to authenticated using (
    exists (select 1 from public.shipments s
            where s.id = shipment_id and s.org_id = (select private.current_org_id()))
  );
create policy "members read checks" on public.checks
  for select to authenticated using (
    exists (select 1 from public.shipments s
            where s.id = shipment_id and s.org_id = (select private.current_org_id()))
  );
create policy "members read tasks" on public.tasks
  for select to authenticated using (
    exists (select 1 from public.shipments s
            where s.id = shipment_id and s.org_id = (select private.current_org_id()))
  );
create policy "members read audit events" on public.audit_events
  for select to authenticated using (
    exists (select 1 from public.shipments s
            where s.id = shipment_id and s.org_id = (select private.current_org_id()))
  );

-- No direct browser writes until A ships validated mutation APIs and policies.
revoke all on table
  public.organizations, public.memberships, public.staff, public.shipments,
  public.containers, public.documents, public.checks, public.tasks,
  public.audit_events from public, anon, authenticated;
grant select on table
  public.organizations, public.memberships, public.staff, public.shipments,
  public.containers, public.documents, public.checks, public.tasks,
  public.audit_events to authenticated;
grant all on table
  public.organizations, public.memberships, public.staff, public.shipments,
  public.containers, public.documents, public.checks, public.tasks,
  public.audit_events to service_role;
